id: P008084
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:00:29.460064
source_metadata:
  id: bdr:W1CZ1146
  title: གཤེད་དམར་ཆོས་སྐོར་
  author: ''
  volumes:
    b85459a39bc9460497a3bc5b65084182:
      image_group_id: I1CZ1553
      title: Volume 1 of gshed dmar chos skor
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
