id: P008084
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1146
  title: གཤེད་དམར་ཆོས་སྐོར་
  author: ''
  volumes:
    57485def8c864875855d82f809138636:
      image_group_id: I1CZ1553
      title: ''
      volume_number: 1
      total_pages: 338
ebook_metadata:
  title: གཤེད་དམར་ཆོས་སྐོར་
  author: ''
  sku: P008084
  cover: cover.jpg
  layers:
  - pagination
