id: P008084
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1146
  title: གཤེད་དམར་ཆོས་སྐོར་
  author: ''
  volumes:
    b85459a39bc9460497a3bc5b65084182:
      image_group_id: I1CZ1553
      title: Volume 1 of gshed dmar chos skor
      volume_number: 1
      total_pages: 338
      base_file: v001.txt
ebook_metadata:
  title: གཤེད་དམར་ཆོས་སྐོར་
  author: ''
  sku: P008084
  cover: cover.jpg
  layers:
  - pagination
